# Generated by Django 5.1.3 on 2024-12-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_image_description_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
